# Generated by Django 5.2.6 on 2025-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='fish_unit',
            field=models.CharField(choices=[('kg', 'Per kg'), ('piece', 'Per piece')], default='kg', help_text='Unit for fish pricing calculation', max_length=10),
        ),
    ]
