# Generated by Django 5.2.6 on 2025-09-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockingevent',
            name='supplier_vendor',
        ),
    ]
