# Generated by Django 5.2.6 on 2025-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='fish_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of fish (pieces) for fish items', null=True),
        ),
    ]
