# Generated by Django 5.2.6 on 2025-09-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_remove_stockingevent_supplier_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='supplier_vendor',
            field=models.ForeignKey(blank=True, help_text='Fish fry supplier if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocking_events', to='fish_farming.vendor'),
        ),
    ]
