# Generated by Django 5.2.6 on 2025-09-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_feed_cost_per_kg_feed_packet_size_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='pieces_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pieces per kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='pieces_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pieces per kg', max_digits=10, null=True),
        ),
    ]
