# Generated by Django 5.2.6 on 2025-09-10 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_add_sampletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='depth_m',
        ),
        migrations.AddField(
            model_name='pond',
            name='depth_ft',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Depth in feet', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incometype',
            name='category',
            field=models.CharField(choices=[('harvest', 'Harvest'), ('seedling', 'Seedling'), ('consulting', 'Consulting'), ('equipment_sales', 'Equipment Sales'), ('services', 'Services'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pond',
            name='area_sqm',
            field=models.DecimalField(decimal_places=3, help_text='Area in square meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pond',
            name='volume_m3',
            field=models.DecimalField(decimal_places=3, help_text='Volume in cubic meters', max_digits=10),
        ),
    ]
