# Generated by Django 5.2.6 on 2025-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_add_fish_unit_to_invoice_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='fish_count',
            field=models.IntegerField(blank=True, help_text='Number of fish (pieces) for fish items', null=True),
        ),
    ]
