# Generated by Django 5.2.6 on 2025-09-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_stockentry_fish_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fishsampling',
            unique_together={('pond', 'date')},
        ),
    ]
