# Generated by Django 5.2.6 on 2025-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_change_fish_count_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='fish_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Per kg'), ('piece', 'Per piece')], help_text='Unit for fish pricing calculation (required for fish items)', max_length=10, null=True),
        ),
    ]
