# Generated by Django 5.2.6 on 2025-09-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_update_fishsampling_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fishsampling',
            unique_together=set(),
        ),
    ]
