# Generated by Django 5.2.6 on 2025-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_add_supplier_vendor_to_stocking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockingevent',
            name='supplier_vendor',
        ),
    ]
