# Generated by Django 5.2.6 on 2025-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_alter_harvest_pieces_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='avg_weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='initial_avg_weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Initial average weight in kg', max_digits=10),
        ),
    ]
