# Generated by Django 5.2.6 on 2025-09-10 10:19

import django.utils.timezone
from django.db import migrations, models
from decimal import Decimal


def convert_area_sqm_to_decimal(apps, schema_editor):
    """Convert existing area_sqm values to area_decimal"""
    Pond = apps.get_model('fish_farming', 'Pond')
    for pond in Pond.objects.all():
        if hasattr(pond, 'area_sqm') and pond.area_sqm:
            # Convert m² to decimal: 1 decimal = 40.46 m²
            area_decimal = Decimal(str(pond.area_sqm)) / Decimal('40.46')
            pond.area_decimal = area_decimal
            pond.save()


def reverse_convert_decimal_to_area_sqm(apps, schema_editor):
    """Convert area_decimal back to area_sqm for rollback"""
    Pond = apps.get_model('fish_farming', 'Pond')
    for pond in Pond.objects.all():
        if hasattr(pond, 'area_decimal') and pond.area_decimal:
            # Convert decimal to m²: 1 decimal = 40.46 m²
            area_sqm = Decimal(str(pond.area_decimal)) * Decimal('40.46')
            pond.area_sqm = area_sqm
            pond.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_update_pond_measurements'),
    ]

    operations = [
        # First, add the new field with a temporary default
        migrations.AddField(
            model_name='pond',
            name='area_decimal',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.5'), help_text='Area in decimal units (1 decimal = 40.46 m²)', max_digits=8),
            preserve_default=False,
        ),
        # Convert existing data
        migrations.RunPython(convert_area_sqm_to_decimal, reverse_convert_decimal_to_area_sqm),
        # Remove the old field
        migrations.RemoveField(
            model_name='pond',
            name='area_sqm',
        ),
    ]
