# Generated by Django 5.2.6 on 2025-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0004_alter_harvest_avg_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='avg_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
