# Generated by Django 5.2.6 on 2025-10-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0004_make_fish_unit_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
