# Generated by Django 5.2.6 on 2025-09-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0004_update_pond_area_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='FeedingAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estimated_fish_count', models.PositiveIntegerField(help_text='Estimated number of fish in pond')),
                ('average_fish_weight_g', models.DecimalField(decimal_places=2, help_text='Average fish weight in grams', max_digits=8)),
                ('total_biomass_kg', models.DecimalField(decimal_places=2, help_text='Total fish biomass in kg', max_digits=10)),
                ('recommended_feed_kg', models.DecimalField(decimal_places=2, help_text='Recommended daily feed amount in kg', max_digits=8)),
                ('feeding_rate_percent', models.DecimalField(decimal_places=2, help_text='Feeding rate as % of biomass', max_digits=5)),
                ('feeding_frequency', models.PositiveIntegerField(default=2, help_text='Recommended feeding frequency per day')),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=2, help_text='Water temperature in Celsius', max_digits=5, null=True)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='summer', max_length=20)),
                ('feed_cost_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg of feed', max_digits=8, null=True)),
                ('daily_feed_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Daily feed cost', max_digits=10, null=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this advice has been applied')),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.ForeignKey(blank=True, help_text='Recommended feed type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish_farming.feedtype')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_advice', to='fish_farming.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FishSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sample_size', models.PositiveIntegerField(help_text='Number of fish sampled')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, help_text='Total weight of sampled fish in kg', max_digits=8)),
                ('average_weight_g', models.DecimalField(decimal_places=2, help_text='Average weight per fish in grams', max_digits=8)),
                ('fish_per_kg', models.DecimalField(decimal_places=2, help_text='Number of fish per kg', max_digits=8)),
                ('growth_rate_g_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Daily growth rate in grams', max_digits=8, null=True)),
                ('condition_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Fish condition factor', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observations and notes about the sampling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_samplings', to='fish_farming.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_samplings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('pond', 'date')},
            },
        ),
    ]
