# Generated by Django 5.2.6 on 2025-09-22 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0004_remove_supplier_vendor_from_stocking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feed_stage',
            field=models.CharField(blank=True, help_text='Feed stage: Starter, Grower, Finisher, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='protein_content',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein content % (for feeds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ItemSales',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_type', models.CharField(choices=[('to_customer', 'To Customer'), ('to_pond', 'To Pond'), ('internal_use', 'Internal Use')], max_length=20)),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sales', to='fish_farming.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sales', to='fish_farming.invoice')),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sales', to='fish_farming.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSalesLine',
            fields=[
                ('sale_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, help_text='Quantity sold/issued', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total line amount', max_digits=12)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv_txn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lines', to='fish_farming.inventorytransactionline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='fish_farming.item')),
                ('item_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fish_farming.itemsales')),
            ],
            options={
                'ordering': ['item_sale', 'sale_line_id'],
            },
        ),
    ]
