# Generated by Django 5.2.6 on 2025-10-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0005_employee_employee_number_employee_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollline',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='payrollline',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payrollline',
            name='gross_salary',
        ),
        migrations.AddField(
            model_name='payrollline',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days absent', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absent deduction (Gross ÷ 30 × absent days)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='festival_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Festival bonus (Eid bonuses)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='full_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly agreed salary', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gratuity/Service benefit', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='harvest_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harvest incentive (Kg × Rate)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='insurance_welfare',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Insurance/Welfare fund', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='loan_advance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loan/Advance repayment', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=8),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime pay (Gross ÷ 208 × 2 × OT hours)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='performance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Performance/Attendance bonus', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='pf_employee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund (Employee contribution)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund (Employer contribution)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='tax_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax (PAYE) as per NBR slab', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total deductions', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total earnings (Full salary + additions)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('BILL', 'Bill'), ('BILL_PAYMENT', 'Bill Payment'), ('INVOICE', 'Invoice'), ('CUST_PAYMENT', 'Customer Payment'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('CHECK', 'Check'), ('INVENTORY', 'Inventory'), ('STOCKING_FEED_MED', 'Stocking/Feed/Medicine'), ('PAYROLL', 'Payroll'), ('MANUAL', 'Manual Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net pay to employee', max_digits=12),
        ),
    ]
