# Generated by Django 5.2.6 on 2025-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0005_update_mortality_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingadvice',
            name='average_fish_weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Average fish weight in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='feedingadvice',
            name='total_biomass_kg',
            field=models.DecimalField(decimal_places=4, help_text='Total fish biomass in kg', max_digits=10),
        ),
    ]
