# Generated by Django 5.2.6 on 2025-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0005_add_fish_sampling_and_feeding_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='biomass_at_feeding_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated fish biomass at time of feeding', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='consumption_rate_kg_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily consumption rate in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='cost_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg of feed', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='feeding_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Feeding rate as % of biomass', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this feeding', max_digits=10, null=True),
        ),
    ]
