# Generated by Django 5.2.6 on 2025-10-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0006_remove_payrollline_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
