# Generated by Django 5.2.6 on 2025-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0006_add_feed_consumption_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='cost_per_kg',
        ),
        migrations.AddField(
            model_name='feed',
            name='cost_per_packet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per packet of feed (25kg)', max_digits=8, null=True),
        ),
    ]
