# Generated by Django 5.2.6 on 2025-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0006_add_item_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineline',
            name='dosage_unit',
            field=models.CharField(blank=True, help_text='Unit for prescribed dosage (mg, ml, g, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='medicineline',
            name='medicine_type',
            field=models.CharField(choices=[('antibiotic', 'Antibiotic'), ('antifungal', 'Antifungal'), ('antiparasitic', 'Antiparasitic'), ('vitamin', 'Vitamin'), ('mineral', 'Mineral'), ('probiotic', 'Probiotic'), ('disinfectant', 'Disinfectant'), ('hormone', 'Hormone'), ('other', 'Other')], default='other', help_text='Type of medicine', max_length=50),
        ),
        migrations.AddField(
            model_name='medicineline',
            name='prescribed_dosage',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Prescribed dosage amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineline',
            name='state_type',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('powder', 'Powder'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('topical', 'Topical'), ('granule', 'Granule'), ('other', 'Other')], default='liquid', help_text='Physical state/form of medicine', max_length=50),
        ),
        migrations.AddField(
            model_name='medicineline',
            name='treatment_type',
            field=models.CharField(choices=[('preventive', 'Preventive'), ('therapeutic', 'Therapeutic'), ('curative', 'Curative'), ('prophylactic', 'Prophylactic'), ('emergency', 'Emergency'), ('routine', 'Routine')], default='therapeutic', help_text='Type of treatment', max_length=50),
        ),
        migrations.AddField(
            model_name='medicineline',
            name='unit_of_measure',
            field=models.CharField(default='ml', help_text='Unit of measure for quantity (ml, g, kg, tablets, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicineline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=12, null=True),
        ),
    ]
