# Generated by Django 5.2.6 on 2025-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0007_medicineline_dosage_unit_medicineline_medicine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineevent',
            name='create_invoice',
            field=models.BooleanField(default=False, help_text='Generate invoice for this medicine event'),
        ),
        migrations.AddField(
            model_name='medicineevent',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Invoice status', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineline',
            name='dosage_unit',
            field=models.CharField(choices=[('mg', 'Milligrams (mg)'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('l', 'Liters (L)'), ('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('units', 'Units'), ('iu', 'International Units (IU)'), ('ppm', 'Parts Per Million (ppm)'), ('other', 'Other')], default='ml', help_text='Unit for prescribed dosage', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicineline',
            name='unit_of_measure',
            field=models.CharField(choices=[('mg', 'Milligrams (mg)'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('l', 'Liters (L)'), ('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('units', 'Units'), ('iu', 'International Units (IU)'), ('ppm', 'Parts Per Million (ppm)'), ('other', 'Other')], default='ml', help_text='Unit of measure for quantity', max_length=50),
        ),
    ]
