# Generated by Django 5.2.6 on 2025-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0007_remove_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='east_ammonia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='East Ammonia (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='east_dissolved_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='East Dissolved Oxygen (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='east_nitrite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='East Nitrite (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='east_ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='East pH'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='east_water_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='East Water Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='north_ammonia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='North Ammonia (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='north_dissolved_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='North Dissolved Oxygen (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='north_nitrite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='North Nitrite (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='north_ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='North pH'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='north_water_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='North Water Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='south_ammonia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='South Ammonia (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='south_dissolved_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='South Dissolved Oxygen (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='south_nitrite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='South Nitrite (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='south_ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='South pH'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='south_water_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='South Water Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='west_ammonia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='West Ammonia (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='west_dissolved_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='West Dissolved Oxygen (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='west_nitrite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='West Nitrite (mg/L)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='west_ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='West pH'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='west_water_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='West Water Temperature (°C)'),
        ),
    ]
