# Generated by Django 5.2.6 on 2025-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0008_medicineevent_create_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Current stock quantity', max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='max_stock_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum stock level', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Minimum stock level for alerts', max_digits=15),
        ),
    ]
