# Generated by Django 5.2.6 on 2025-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0008_medicaldiagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_considerations',
            field=models.TextField(blank=True, help_text='Medical considerations and adjustments made to feeding advice'),
        ),
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_diagnostics',
            field=models.ManyToManyField(blank=True, help_text='Related medical diagnostics that influenced this feeding advice', related_name='feeding_advice', to='fish_farming.medicaldiagnostic'),
        ),
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_warnings',
            field=models.JSONField(default=list, help_text='Medical warnings and recommendations for this feeding advice'),
        ),
    ]
