# Generated by Django 5.2.6 on 2025-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0008_add_four_direction_water_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldiagnostic',
            name='disease_name',
            field=models.TextField(help_text='Possible Disease'),
        ),
    ]
