# Generated by Django 5.2.6 on 2025-09-23 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0009_item_current_stock_item_max_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_of_goods_sold_account',
            field=models.ForeignKey(blank=True, help_text='Cost of Goods Sold account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_items', to='fish_farming.account'),
        ),
    ]
