# Generated by Django 5.2.6 on 2025-09-19 11:05

from django.db import migrations
from django.contrib.auth.models import User


def assign_species_to_users(apps, schema_editor):
    Species = apps.get_model('fish_farming', 'Species')
    
    # Get the first user, or create a default admin user if none exists
    try:
        user = User.objects.first()
        if not user:
            user = User.objects.create_user(
                username='admin',
                email='admin@example.com',
                password='admin123',
                is_staff=True,
                is_superuser=True
            )
        
        # Assign all species without a user to the first user
        Species.objects.filter(user__isnull=True).update(user=user)
        print(f"Assigned {Species.objects.filter(user=user).count()} species to user {user.username}")
        
    except Exception as e:
        print(f"Error assigning species to users: {e}")


def reverse_assign_species_to_users(apps, schema_editor):
    # This is a data migration, so we don't need to reverse it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0010_add_user_to_species'),
    ]

    operations = [
        migrations.RunPython(assign_species_to_users, reverse_assign_species_to_users),
    ]
