# Generated by Django 5.2.6 on 2025-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0010_item_cost_of_goods_sold_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_feed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_medicine',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_species',
        ),
    ]
