# Generated by Django 5.2.6 on 2025-09-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0011_remove_item_classifications'),
    ]

    operations = [
        # First, remove the many-to-many relationship
        migrations.RemoveField(
            model_name='vendor',
            name='categories',
        ),
        # Then delete the through model
        migrations.DeleteModel(
            name='VendorVendorCategory',
        ),
        # Finally delete the VendorCategory model
        migrations.DeleteModel(
            name='VendorCategory',
        ),
    ]
