# Generated by Django 5.2.6 on 2025-09-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0011_assign_species_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='auth.user'),
        ),
    ]
