# Generated by Django 5.2.6 on 2025-09-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0016_modify_income_type_hierarchical'),
    ]

    operations = [
        # First remove foreign key columns
        migrations.RemoveField(
            model_name='vendor',
            name='terms_default',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms',
        ),
        # Then delete the PaymentTerms model
        migrations.DeleteModel(
            name='PaymentTerms',
        ),
    ]
