# Generated by Django 5.2.6 on 2025-09-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0017_auto_20250923_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pond',
            field=models.ForeignKey(blank=True, help_text='Required for Internal Pond type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='fish_farming.pond'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
