# Generated by Django 5.2.6 on 2025-09-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0018_add_pond_to_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('terms_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Net 30, Due on receipt', max_length=100, unique=True)),
                ('day_count', models.PositiveIntegerField(help_text='Number of days for payment')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish_farming.paymentterms'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fish_farming.paymentterms'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='terms_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='fish_farming.paymentterms'),
        ),
    ]
