# Generated by Django 5.2.6 on 2025-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0019_restore_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(help_text='Auto-generated bill number', max_length=100),
        ),
    ]
