# Generated by Django 5.2.6 on 2025-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0020_add_auto_bill_number_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='txn_type',
            field=models.CharField(choices=[('RECEIPT_WITH_BILL', 'Receipt with Bill'), ('RECEIPT_NO_BILL', 'Receipt without Bill'), ('ADJUSTMENT', 'Adjustment'), ('ISSUE_TO_POND', 'Issue to Pond'), ('SALE_TO_CUSTOMER', 'Sale to Customer')], max_length=20),
        ),
    ]
