# Generated by Django 5.2.6 on 2025-09-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0021_add_sale_to_customer_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='leasing_date',
            field=models.DateField(blank=True, help_text='Date when pond was leased', null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='rate_per_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leasing rate per decimal', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='remaining_period',
            field=models.IntegerField(blank=True, help_text='Remaining leasing period in days', null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='total_leasing_money',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total leasing amount paid', max_digits=12, null=True),
        ),
    ]
