# Generated by Django 5.2.6 on 2025-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0022_pond_leasing_date_pond_rate_per_decimal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='remaining_period',
        ),
        migrations.AddField(
            model_name='pond',
            name='leasing_end_date',
            field=models.DateField(blank=True, help_text='Date when pond leasing ends', null=True),
        ),
        migrations.AlterField(
            model_name='pond',
            name='total_leasing_money',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total leasing amount (auto-calculated: area × rate)', max_digits=12, null=True),
        ),
    ]
