# Generated by Django 5.2.6 on 2025-09-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0024_auto_20250924_1216'),
    ]

    operations = [
        # Add the new species field (nullable first)
        migrations.AddField(
            model_name='stockingline',
            name='species',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_lines', to='fish_farming.species', help_text='Fish species stocked'),
        ),
        
        # Remove the old item field
        migrations.RemoveField(
            model_name='stockingline',
            name='item',
        ),
        
        # Make the species field non-nullable
        migrations.AlterField(
            model_name='stockingline',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_lines', to='fish_farming.species', help_text='Fish species stocked'),
        ),
    ]
