# Generated by Django 5.2.6 on 2025-09-24 08:16

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0025_auto_20250924_1249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='species',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fish_farming.species'),
        ),
        migrations.CreateModel(
            name='CustomerStock',
            fields=[
                ('customer_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, help_text='Current stock quantity', max_digits=15)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, help_text='Minimum stock level for alerts', max_digits=15)),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum stock level', max_digits=15, null=True)),
                ('unit', models.CharField(help_text='Unit of measurement (kg, pcs, bags, etc.)', max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fish_farming.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stocks', to='fish_farming.item')),
                ('pond', models.ForeignKey(blank=True, help_text='Pond this stock belongs to (for internal customers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='fish_farming.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Stock',
                'verbose_name_plural': 'Customer Stocks',
                'ordering': ['customer', 'item'],
                'unique_together': {('user', 'customer', 'item')},
            },
        ),
        migrations.AddField(
            model_name='feedingline',
            name='customer_stock',
            field=models.ForeignKey(blank=True, help_text='Customer/pond stock used for feeding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_lines', to='fish_farming.customerstock'),
        ),
    ]
