# Generated by Django 5.2.6 on 2025-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0026_alter_species_options_alter_species_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('chemical', 'Chemical'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
