# Generated by Django 5.2.6 on 2025-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0028_auto_20250924_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gallon_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gallon size in litres (e.g., 5, 10, 20)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='packet_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet size in kg (e.g., 10, 25)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(help_text='kg, packet, litre, gallon, pieces', max_length=20),
        ),
    ]
