# Generated by Django 5.2.6 on 2025-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0029_item_gallon_size_item_packet_size_alter_item_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingevent',
            name='amount_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in kg (calculated or direct input)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='feeding_time',
            field=models.TimeField(blank=True, help_text='Time of feeding', null=True),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='packet_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of packets used', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedingevent',
            name='packet_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of each packet in kg', max_digits=10, null=True),
        ),
    ]
