# Generated by Django 5.2.6 on 2025-09-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0030_add_feeding_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingevent',
            name='feed_item',
            field=models.ForeignKey(blank=True, help_text='Feed item used', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_events', to='fish_farming.item'),
        ),
    ]
