# Generated by Django 5.2.6 on 2025-09-24 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0031_add_feed_item_to_feeding_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity added', max_digits=15)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this entry', max_digits=12, null=True)),
                ('entry_date', models.DateField(help_text='Date when stock was added')),
                ('supplier', models.CharField(blank=True, help_text='Supplier name', max_length=200)),
                ('batch_number', models.CharField(blank=True, help_text='Batch or lot number', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date if applicable', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='fish_farming.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
