# Generated by Django 5.2.6 on 2025-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0032_add_stock_entry_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gallon_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='packet_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uom',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='gallon_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gallon size in litres (e.g., 5, 10, 20)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='packet_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet size in kg (e.g., 10, 25)', max_digits=10, null=True),
        ),
    ]
