# Generated by Django 5.2.6 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0033_remove_uom_from_item_add_to_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='gallon_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gallon size in litres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billline',
            name='packet_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet size in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billline',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement (kg, packet, pieces, etc.)', max_length=20),
        ),
    ]
