# Generated by Django 5.2.6 on 2025-09-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0034_add_uom_fields_to_billline'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='kg', help_text='Unit of measurement', max_length=20),
        ),
    ]
