# Generated by Django 5.2.6 on 2025-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0035_add_unit_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='gallon_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gallon size in litres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='packet_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet size in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement (kg, packet, pieces, etc.)', max_length=20),
        ),
    ]
