# Generated by Django 5.2.6 on 2025-09-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0036_add_unit_fields_to_invoice_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingevent',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Fish species being fed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_events', to='fish_farming.species'),
        ),
    ]
