# Generated by Django 5.2.6 on 2025-09-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0037_add_species_to_feeding_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineevent',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Fish species being treated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_events', to='fish_farming.species'),
        ),
    ]
