# Generated by Django 5.2.6 on 2025-09-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0038_add_species_to_medicine_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineevent',
            name='species',
        ),
    ]
