# Generated by Django 5.2.6 on 2025-09-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0039_remove_species_from_medicine_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineevent',
            name='create_invoice',
        ),
        migrations.RemoveField(
            model_name='medicineevent',
            name='invoice_status',
        ),
        migrations.AddField(
            model_name='medicineevent',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Amount of medicine applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineevent',
            name='medicine_item',
            field=models.ForeignKey(blank=True, help_text='Medicine item applied', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_events', to='fish_farming.item'),
        ),
    ]
