# Generated by Django 5.2.6 on 2025-09-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0040_simplify_medicine_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayment',
            name='deposit_account',
        ),
    ]
