# Generated by Django 5.2.6 on 2025-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0041_remove_deposit_account_from_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
