# Generated by Django 5.2.6 on 2025-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0042_make_deposit_total_amount_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_stock_in_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text="Total stock in item's unit", max_digits=15),
        ),
        migrations.AddField(
            model_name='item',
            name='total_stock_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total stock in kg', max_digits=15),
        ),
    ]
