# Generated by Django 5.2.6 on 2025-09-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0043_add_total_stock_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_stock_in_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_stock_kg',
        ),
    ]
