# Generated by Django 5.2.6 on 2025-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0044_remove_item_total_stock_in_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('chemical', 'Chemical'), ('fish', 'Fish'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50),
        ),
    ]
