# Generated by Django 5.2.6 on 2025-09-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0045_add_fish_fields_to_invoice_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, help_text='Line number for fish items', null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pond',
            field=models.ForeignKey(blank=True, help_text='Pond for fish items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='fish_farming.pond'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Species for fish items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='fish_farming.species'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in kg for fish items', max_digits=10, null=True),
        ),
    ]
