from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
# Core Aquaculture APIs
router.register(r'ponds', views.PondViewSet)
router.register(r'species', views.SpeciesViewSet)
router.register(r'stocking', views.StockingViewSet)
router.register(r'daily-logs', views.DailyLogViewSet)
router.register(r'feed-types', views.FeedTypeViewSet)
router.register(r'feeds', views.FeedViewSet)
router.register(r'sample-types', views.SampleTypeViewSet)
router.register(r'sampling', views.SamplingViewSet)
router.register(r'mortality', views.MortalityViewSet)
router.register(r'harvests', views.HarvestViewSet)
router.register(r'expense-types', views.ExpenseTypeViewSet)
router.register(r'income-types', views.IncomeTypeViewSet)
router.register(r'expenses', views.ExpenseViewSet)
router.register(r'incomes', views.IncomeViewSet)
router.register(r'inventory-feed', views.InventoryFeedViewSet)
router.register(r'treatments', views.TreatmentViewSet)
router.register(r'alerts', views.AlertViewSet)
router.register(r'settings', views.SettingViewSet)
router.register(r'feeding-bands', views.FeedingBandViewSet)
router.register(r'env-adjustments', views.EnvAdjustmentViewSet)
router.register(r'kpi-dashboard', views.KPIDashboardViewSet)
router.register(r'fish-sampling', views.FishSamplingViewSet)
router.register(r'feeding-advice', views.FeedingAdviceViewSet)
router.register(r'survival-rates', views.SurvivalRateViewSet)
router.register(r'medical-diagnostics', views.MedicalDiagnosticViewSet)
router.register(r'target-biomass', views.TargetBiomassViewSet, basename='target-biomass')

# Business Management APIs
router.register(r'payment-terms', views.PaymentTermsViewSet)
router.register(r'customers', views.CustomerViewSet)
router.register(r'accounts', views.AccountViewSet)
router.register(r'vendors', views.VendorViewSet)
router.register(r'item-categories', views.ItemCategoryViewSet)
router.register(r'items', views.ItemViewSet)
router.register(r'stock-entries', views.StockEntryViewSet)
router.register(r'bills', views.BillViewSet)
router.register(r'bill-lines', views.BillLineViewSet)
router.register(r'invoices', views.InvoiceViewSet)
router.register(r'invoice-lines', views.InvoiceLineViewSet)
router.register(r'customer-payments', views.CustomerPaymentViewSet)
router.register(r'customer-payment-applies', views.CustomerPaymentApplyViewSet)
router.register(r'bill-payments', views.BillPaymentViewSet)
router.register(r'customer-stocks', views.CustomerStockViewSet)
router.register(r'deposits', views.DepositViewSet)
router.register(r'inventory-transactions', views.InventoryTransactionViewSet)
router.register(r'inventory-transaction-lines', views.InventoryTransactionLineViewSet)
router.register(r'item-sales', views.ItemSalesViewSet)
router.register(r'item-sales-lines', views.ItemSalesLineViewSet)
router.register(r'stocking-events', views.StockingEventViewSet)
router.register(r'feeding-events', views.FeedingEventViewSet)
router.register(r'feeding-lines', views.FeedingLineViewSet)
router.register(r'medicine-events', views.MedicineEventViewSet)
router.register(r'medicine-lines', views.MedicineLineViewSet)
router.register(r'stock-levels', views.StockLevelViewSet, basename='stock-levels')
router.register(r'other-pond-events', views.OtherPondEventViewSet)
router.register(r'employees', views.EmployeeViewSet)
router.register(r'payroll-runs', views.PayrollRunViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
